#TP5
USE TP1;

#1 
SELECT *
FROM IMOVEL AS I
WHERE I.CD_BAIRRO = (SELECT CD_BAIRRO FROM IMOVEL WHERE CD_IMOVEL = 2)
AND CD_IMOVEL <> 2;

#2 
SELECT I.* 
FROM IMOVEL AS I
WHERE VL_PRECO > (SELECT AVG(VL_PRECO) FROM IMOVEL);

#3
SELECT C.* 
FROM COMPRADOR AS C
WHERE 70000 < ALL(SELECT O.VL_OFERTA FROM OFERTA AS O);
 
#4
SELECT DISTINCT * 
FROM IMOVEL AS I
WHERE I.VL_PRECO > (SELECT AVG(VL_OFERTA) FROM OFERTA);

#5
SELECT * 
FROM IMOVEL AS I, BAIRRO AS B
WHERE I.CD_BAIRRO = B.CD_BAIRRO
AND VL_PRECO > (SELECT AVG(VL_PRECO) FROM IMOVEL);

#6 CONCERTAR (mesmo)
SELECT *, MAX(VL_PRECO)
FROM IMOVEL AS I
WHERE I.VL_PRECO > ALL(SELECT AVG(I.VL_PRECO) FROM IMOVEL AS I)
GROUP BY CD_BAIRRO, CD_CIDADE, SG_ESTADO;

#7
SELECT *
FROM IMOVEL AS I, OFERTA AS O
WHERE I.VL_PRECO <= O.VL_OFERTA;

#8 
SELECT I.* 
FROM IMOVEL AS I 
WHERE I.VL_PRECO = ALL (SELECT MIN(VL_PRECO) FROM IMOVEL WHERE CD_VENDEDOR = I.CD_VENDEDOR);

#9
SELECT * 
FROM OFERTA AS O
WHERE O.VL_OFERTA < ALL(SELECT O.VL_OFERTA FROM OFERTA O WHERE O.CD_COMPRADOR = 2);

#10
SELECT *
FROM IMOVEL AS I
WHERE I.CD_CIDADE = (SELECT CD_CIDADE FROM IMOVEL WHERE CD_VENDEDOR = 3)
AND I.SG_ESTADO = (SELECT SG_ESTADO FROM IMOVEL WHERE CD_VENDEDOR = 3)
AND I.CD_VENDEDOR <> 3;

#11
SELECT B.NM_BAIRRO
FROM BAIRRO AS B
WHERE B.CD_BAIRRO = (SELECT CD_BAIRRO FROM IMOVEL WHERE CD_IMOVEL = 5)
AND B.CD_CIDADE = (SELECT CD_CIDADE FROM IMOVEL WHERE CD_IMOVEL = 5)
AND B.SG_ESTADO = (SELECT SG_ESTADO FROM IMOVEL WHERE CD_IMOVEL = 5);

